# Generated by Django 3.0.5 on 2020-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newscatwise',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('publishedAt', models.DateField(blank=True, default='datetime.date.today()', null=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(default='')),
                ('author', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Newscountrywise',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('publishedAt', models.DateField(blank=True, default='datetime.date.today()', null=True)),
                ('country', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(default='')),
                ('author', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newslist',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('publishedAt', models.DateField(blank=True, default='datetime.date.today()', null=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField(default='')),
                ('author', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
