# Generated by Django 3.0.5 on 2020-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscatwise',
            name='content',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='newscatwise',
            name='description',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='newscountrywise',
            name='content',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='newscountrywise',
            name='description',
            field=models.CharField(max_length=280),
        ),
    ]
