# Generated by Django 3.0.5 on 2020-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200414_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscatwise',
            name='description',
            field=models.CharField(default='Not Available Now', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='newscountrywise',
            name='description',
            field=models.CharField(default='Not Available Now', max_length=280, null=True),
        ),
    ]
