# Generated by Django 3.0.5 on 2020-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20200414_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='author',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
